languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "Yuizen"
copyright = "© Bastelcolor"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "Portfolio of BastelColor"

[params.author]
  name = "BastelColor"
  image = "img/author.png"
  headline = "Creator"
  bio = "Nothing to bio"
  links = [
   { twitter = "https://twitter.com/bastelcolor"},
   { youtube = "https://www.youtube.com/@bastelcolor"},
   { misskey = "https://misskey.io/@BastelColor" }
  ]